### ISSUE TITLE
(Question) Why service objects can hold multiple errors?

### ISSUE THREAD

**Issue by TangRufus** [envato/aldous#14]
Since 
- the first error is immediately *rescued* by [Service::Wrapper#perform!](https://github.com/envato/aldous/blob/master/lib/aldous/service/wrapper.rb#L30)
- `aldous` seems encourage to return `Result::Failure` (or raise errors) as soon as possible

Why a service object can hold multiple errors?

Correct me if I am wrong. Thanks!

**Comment by skorks** [comment]
I am not 100% sure I understand your question. A service object itself doesn't hold/store any errors.
A result object can store a list of errors (or error messages), perhaps you're referring to that?

You're right that Aldous does encourage you to short-circuit the perform method, by returning `Result::Failure` as soon as you can, but you don't want to be locked in to doing things a specific way. 

You may choose to collect a number of errors (e.g. by rescuing several statements separately) and then return them all at once, which is why a `Result::Failure` object takes a list of errors. The point is to encourage the usage of specific patterns, but not to architecturally lock you in to doing things in specific ways. If you want/need to do something different you should be able to.

Does that answer your question?

**Comment by TangRufus** [comment]
Yes, thanks!!!
